### ISSUE TITLE
Is there any way to use exposed vars without `window.{varname}`?

### ISSUE THREAD

**Issue by gobwas** [thlorenz/exposify#13]
For example, Im writing some jquery plugin in cjs style, then I bundling it:

```
(function(factory) {
  if (isNode) { ... factory(jQuery) } else if (isAMD) {... factory(jQuery) } else {... factory(jQuery) }
})(function(jQuery){
  return require('my_plugin');
});

```

Source of 'my_plugin' module:

```js
module.exports = require("jquery");
```

And this code exposed after bundle like:

```js
bundler.transform('exposify', {
  expose: {
    jquery: "jQuery"
  }
});
```

```js
module.exports = (window.jQuery);
```

But I just want to use it like:

```js
module.exports = (jQuery);
```

because of umd wrapper above.

Thanks! =)

**Comment by bendrucker** [comment]
You can use [literalify](https://github.com/pluma/literalify), but I wouldn't recommend it. 

There are a few problems here. The first and most important is that you're expecting the code of `my_plugin` to change, but that's not how transforms work. You can tell Browserify to apply a transform globally (across all traversed code in `node_modules`) but that has caveats and costs that come with it. 

Then there's the issue of the right way to solve this problem locally in a project (i.e. in `my_plugin`). That would be to write a transform there that shares some code from exposify (specifically use the detective and has-require dependencies). You'd use the `ignore` option when bundling and then place some manual logic for loading jQuery.

I'm willing to write a transform to do this if we can get on the same page regarding the use case and requirements.
