### ISSUE TITLE
Update version of replace-requires to work with requires that have slashes

### ISSUE THREAD

**Issue by stubailo** [thlorenz/exposify#15]
Version 1.0.3 has a fix: https://github.com/bendrucker/replace-requires/issues/1

This will make it possible to replace `require('react/addons')` using this transform.

**Comment by stubailo** [comment]
Wow, super fast response. Thanks!

**Comment by bendrucker** [comment]
:)

**Comment by stubailo** [comment]
Would be awesome to get this published to NPM!

**Comment by bendrucker** [comment]
Thorsten will get to it in the next couple of days. Shouldn't matter though. A fresh install will get the updated patch versions downstream.

**Comment by stubailo** [comment]
Oh, right - good point.
