### ISSUE TITLE
bump version

### ISSUE THREAD

**Issue by boneskull** [thlorenz/exposify#17]
I need @bendrucker 's patch...

**Comment by cuth** [comment]
The command line is broken without d30ec8c2eace1832abc235d188b1a08b30836177.

**Comment by bendrucker** [comment]
@thlorenz Can you add me on npm so I can take care of this?

**Comment by thlorenz** [comment]
@bendrucker done.
Sorry for the delay - travelling lots these days ;)

**Comment by bendrucker** [comment]
No worries! :foggy: > :octocat:

**Comment by bendrucker** [comment]
ac6b5e083835818131f0afe0c79e52b1ebda61cf
