### ISSUE TITLE
How to make exposify work on files that have JSX?

### ISSUE THREAD

**Issue by mitermayer** [thlorenz/exposify#18]
exposify seems to not work with files that have JSX

**Comment by bendrucker** [comment]
No idea to be perfectly honest. If you transform them to valid JS beforehand by ordering your transforms correctly it should just work. If you can determine that this is an exposify issue and give us more to go on, happy to reopen.

**Comment by mitermayer** [comment]
Changed to use literalify instead since I could not get around on how to make exposify work.

**Comment by bendytree** [comment]
+1 

[`literalify`](https://github.com/pluma/literalify) worked, thanks for the tip

**Comment by bendrucker** [comment]
> reactify first, it would fail since it would not be able to require the shimmed components

Not sure what this means. If you guys are up for doing a repro of this issue, I want to understand why the standard "transform to ES5 then run other AST transforms like exposify" strategy doesn't work with this particular setup. 

I'm glad literalify works w/ that setup. Exposify has 100x the monthly download count so I want to address this in exposify and help the max number of people. I'd be happy to get to the bottom of this issue and could really use your help.

**Comment by bendrucker** [comment]
If either of you can contribute to solving this I'll go ahead and reopen
