### ISSUE TITLE
Allow config on call

### ISSUE THREAD

**Issue by andrezsanchez** [thlorenz/exposify#5]
I feel like it would be more conventional and convenient to allow setting the options when you call the function like other libraries do (eg. [reactify](https://github.com/andreypopp/reactify), [envify](https://github.com/hughsk/envify))

So you could just do
```javascript
exposify({ jquery: '$', three: 'THREE' });
```

**Comment by thlorenz** [comment]
PR to add that is pending, will add soon and ping you back when it's done.

**Comment by thlorenz** [comment]
PR merged and published.
