### ISSUE TITLE
Confused on Documentation

### ISSUE THREAD

**Issue by nkoterba** [thlorenz/exposify#6]
In the ReadMe for exposify it says:
```javascript
Or use it via browserify-shim which allows you to provide exposify config inside your package.json among other features.
```

I'm really confused where in my package.json I would set exposify.config using browserify-shim.   Can you provide an example or show a simple setup in the main page Readme?

Is it in the browserify transform option:
```javascript
  "browserify": {
    "transform": [
      "browserify-shim",
      "exposify" <-- HERE
    ]
  },
```

Or perhaps in the browserify-shim config itself:
```javascript
  "browserify-shim": {
    "jquery": "global:jQuery",
    "angular": {
      "exports": "angular",
      "depends": [
        "jquery:jQuery"
      ]
    },
    "hammer": "HammerJS",
    "kendo": {
      "depends": [
        "jquery:jQuery"
      ]
    }
  },
```

Thanks in advance!

**Comment by bendrucker** [comment]
browserify-shim uses exposify under the hood for cases where you set `global:{name}` in your config. It also does the dramatically more complicated work of shimming badly behaved packages. You don't insert exposify into your config or use it at all if you're using b-shim.
